### ISSUE TITLE
$filter, $search returning different values for same criteria

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/microsoft-graph-docs#246] opened 2016-04-13 21:30 UTC
Thanks to @jennifermarsman for sharing this feedback 👍

I would expect the following queries to be equivalent:

```
GET https://graph.microsoft.com/v1.0/me/messages?$filter=from/emailAddress/address eq 'user@example.com' 
```

```
GET https://graph.microsoft.com/v1.0/me/messages?$search="from:user@example.com"
```

Testing w/ production data, the first query returns an empty set while the second query returns emails. The second query returns the expected data. 

Examples taken from [here](http://graph.microsoft.io/en-us/docs/overview/query_parameters)

**Comment by iambmelt** [comment] 2016-04-13 21:31
Are these *really* equivalent? Do the differences in these two result sets reflect a service issue?

**Comment by marych** [comment] 2016-04-26 01:31
There is known issue related to filtering messages by the from property for addresses of the same domain as that of the user running the request - see https://github.com/OfficeDev/microsoft-graph-docs/issues/121. A fix for this is being rolled out and should complete for all mailboxes in about a week.

**Comment by iambmelt** [comment] 2016-04-26 05:49
Thanks for the update @marych -- this is helpful 👍

**Comment by iambmelt** [comment] 2016-05-03 09:55
Hi @marych - Just following up on this issue to make sure it gets closed once resolved. Short of manual testing, is there some way @jennifermarsman and I can be informed when the fix goes live? Thank you!

**Comment by marych** [comment] 2016-05-06 00:01
Hi @iambmelt - due to a regression in another area this change needed to be reverted. I'll make an update here when a corrected fix is ready. I'm sorry for the delay.

**Comment by marych** [comment] 2016-09-01 13:40
The fix was deployed and I can no longer repro the issue.

**Closed by marych** 2016-09-01 13:40 UTC
